 const USERS_MESSAGES ={
  SUCCESS:'success',
  VALIDATION_ERROR:'Validation error',
  NAME_IS_REQUIRED:'Name is required',
  USER_NOT_FOUND:'User not found',
  NAME_MUST_BE_A_STRING:'Name must be a string',
  INVALID_EMAIL:'Invalid email address',
  EMAIL_IS_REQUIRED:'Email is required',
  EMAIL_MUST_BE_A_STRING:'Email must be a string',
  EMAIL_MUST_BE_A_VALID_EMAIL:'Email must be a valid email',
  PASSWORD_IS_REQUIRED:'Password is required',
  PASSWORD_MUST_BE_A_STRING:'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50:'Password length must be',
  NAME_LENGTH_MUST_BE_FROM_6_TO_50:'NAME_LENGTH_MUST_BE_FROM_6_TO_50',
  EMAIL_IS_EXIT:'email_is_exit',
  PASSWORD_MUST_BE_A_STRONG_PASSWORD:'Password must be a',
  CONFIRM_PASSWORD_IS_REQUIRED:'Confirm Password must be',
  CONFIRM_PASSWORD_MUST_BE_A_STRING:'CONFIRM_PASSWORD_MUST_BE_A_STRING',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50:'CONFIRM_PASSW',
  ACCESS_TOKEN_IS_INVALID:'Access token must be',
  ACCESS_TOKEN_IS_REQUIRED:'Access token must be a required',
  REFRESH_TOKEN_IS_REQUIRED:'Refresh token must be a required',
  REFRESH_TOKEN_IS_INVALID:'Refresh token must be',
  USED_REFRESH_TOKEN_OR_NOT_EXIT:'refresh token is not exits'
 } as const 
export default USERS_MESSAGES 